export const translations = {
  vi: {
    home: "Trang Chủ",
    genres: "Thể Loại",
    countries: "Quốc Gia",
    movies: "Phim Lẻ",
    series: "Phim Bộ",
    favorites: "Yêu Thích",
    search_placeholder: "Tìm phim...",
    welcome: "Chào mừng",
    profile: "Trang cá nhân",
    logout: "Đăng xuất",
    login: "Đăng Nhập",
    register: "Đăng Ký",
    featured_movie: "Phim Nổi Bật",
    play_now: "Xem Phim Ngay",
    details: "Xem Chi Tiết",
    trending_week: "Xu hướng tuần",
    popular_keywords: "Từ khóa phổ biến",
    search_home_placeholder: "Tìm kiếm phim, diễn viên...",
    search_btn: "Tìm Kiếm",
    my_collection: "Bộ sưu tập của tôi",
    empty_fav: "Danh sách trống",
    explore_now: "Khám phá ngay",
    update_profile: "Cập nhật thông tin",
    username: "Tên người dùng",
    email: "Email",
    password: "Mật khẩu",
    new_password: "Mật khẩu mới",
    save_changes: "Lưu Thay Đổi",
    cancel: "Hủy",
    edit_profile: "Chỉnh Sửa Hồ Sơ",
    account_settings: "Cài đặt tài khoản",
    stats_fav: "Yêu thích",
    stats_comm: "Bình luận",
    stats_rate: "Đánh giá",
    community_rating: "Đánh giá từ cộng đồng",
    your_thought: "Chia sẻ suy nghĩ của bạn về bộ phim này...",
    send_rating: "Gửi Đánh Giá",
    feeling: "Cảm nhận:",
    footer_desc: "Khám phá hàng triệu bộ phim, chương trình truyền hình và con người. Trải nghiệm ngay. Xây dựng với MERN Stack.",
    explore: "Khám phá",
    support: "Hỗ trợ",
    newsletter: "Bản tin",
    newsletter_desc: "Nhận cập nhật phim mới nhất.",
    email_addr: "Địa chỉ Email",
    join: "Tham gia",
    all_genres: "Tất cả thể loại",
    release_year: "Năm phát hành",
    login_title: "Chào mừng trở lại",
    login_subtitle: "Đăng nhập để tiếp tục trải nghiệm thế giới điện ảnh.",
    no_account: "Chưa có tài khoản?",
    have_account: "Đã có tài khoản?",
    register_title: "Tạo tài khoản mới",
    register_subtitle: "Tham gia cùng cộng đồng yêu phim MovieZone.",
    remember_me: "Ghi nhớ tôi",
    forgot_password: "Quên mật khẩu?",
    social_login: "Hoặc đăng nhập với",
    error_required: "Trường này là bắt buộc",
    error_email: "Email không hợp lệ",
    error_password_min: "Mật khẩu phải có ít nhất 6 ký tự",
    loading: "Đang tải...",
    no_results: "Không tìm thấy kết quả phù hợp",
    admin_dashboard: "Bảng điều khiển Admin",
    total_users: "Tổng người dùng",
    total_movies: "Tổng phim",
    requests: "Duyệt Quyền",
    manage_movies: "Đăng Phim",
    recent_comments: "Bình luận mới nhất",
    back_to_top: "Lên đầu trang",
    success_update: "Thành công! Thông tin đã được cập nhật.",
    error_update: "Thất bại! Không thể cập nhật thông tin.",
    logged_out: "Đã đăng xuất khỏi hệ thống.",
    invalid_credentials: "Thông tin đăng nhập không chính xác",
    overview: "Tổng quan",
    cast: "Diễn viên",
    recommendations: "Phim tương tự",
    trailers: "Trailers & Teasers",
    rating: "Đánh giá",
    status: "Trạng thái",
    runtime: "Thời lượng",
    country: "Quốc gia",
    minutes: "phút",
    release_date: "Ngày phát hành",
    fav_removed: "Đã xóa khỏi danh sách yêu thích.",
    fav_added: "Đã thêm vào danh sách yêu thích thành công!",
    fav_error: "Có lỗi xảy ra, vui lòng thử lại sau.",
    empty_fav_desc: "Bạn chưa có bộ phim yêu thích nào. Hãy khám phá và nhấn vào icon trái tim để lưu lại nhé!",
    movies_count: "Phim",
    fav_description: "Nơi lưu trữ những bộ phim bạn yêu thích nhất.",
    login_required_fav: "Vui lòng đăng nhập để lưu phim yêu thích",
    login_required_comm: "Vui lòng đăng nhập để gửi bình luận",
    comment_posted: "Đã đăng bình luận",
    comment_error: "Lỗi bình luận",
    actors: "Diễn Viên",
    awards: "Giải Thưởng",
    help_center: "Trung tâm trợ giúp",
    terms: "Điều khoản sử dụng",
    privacy: "Chính sách bảo mật",
    content_policy: "Chính sách nội dung",
    welcome_back: "Chào mừng bạn quay trở lại với MovieZone!",
    reg_success: "Đăng ký thành công! Chào mừng bạn gia nhập MovieZone.",
    logout_success: "Đã đăng xuất thành công. Hẹn gặp lại!",
    upload_success: "Thành công! Ảnh đại diện đã được cập nhật.",
    upload_error: "Lỗi! Tải ảnh lên thất bại.",
    file_too_large: "Ảnh quá lớn! Vui lòng chọn ảnh dưới 2MB.",
    profile_updated: "Hồ sơ của bạn đã được cập nhật thành công!",
    avatar_updated: "Thành công! Ảnh đại diện đã được thay đổi.",
    no_trailer: "Chưa có trailer cho phim này",
     copied_link: "Đã sao chép liên kết phim!",
     save_fav: "Lưu Phim",
     saved_fav: "Đã Lưu",
     liked: "Đã thích",
     share: "Chia Sẻ",
    views: "Lượt Xem",
    no_comments: "Chưa có bình luận nào.",
    no_watch_history: "Chưa có lịch sử xem phim.",
    no_comments_yet: "Bạn chưa để lại bình luận nào.",
    no_liked_comments: "Bạn chưa thả tim bình luận nào.",
    no_replies_yet: "Bạn chưa phản hồi bình luận nào.",
    view_on_movie: "Xem tại phim",
    view_source: "Xem nguồn",
    view_movie: "Xem phim",
    replied_to: "Phản hồi bình luận của",
    you_liked_this: "Bạn đã thả tim",
    withdraw: "Thu hồi",
    you_wrote: "Bạn đã viết",
    like: "Thích",
    reply: "Phản hồi",
    admin_manage_users: "Quản Lý Người Dùng",
    account: "Tài khoản",
    recently_updated: "Phim Mới Cập Nhật",
    hot_series: "Phim Bộ Hot",
    new_movies: "Phim Lẻ Mới",
    top_rated: "Top Phim Đánh Giá",
    explore_all: "Khám phá tất cả phim",
    explore_more: "Khám phá thêm",
    view_all_results: "Xem tất cả kết quả tìm kiếm",
    loading_experience: "Đang tải trải nghiệm...",
    save: "Lưu",
    saving: "Đang lưu...",
    admin_system: "Hệ thống quản trị nội dung",
    preview_site: "Xem trang User",
    pending_requests: "Yêu cầu chờ duyệt",
    manage_comments: "Quản lý bình luận",
    add_banner: "Thêm Banner",
    add_movie: "Thêm Phim",
    save_banner: "Lưu Banner",
    save_movie: "Lưu Phim",
    select_movie: "Chọn phim liên kết (Tùy chọn)",
    external_link: "Link liên kết ngoài (Tùy chọn)",
    title: "Tiêu đề",
    description: "Mô tả",
    poster_url: "URL Ảnh Poster",
    trailer_url: "URL Trailer (Youtube)",
    runtime_placeholder: "Thời lượng (VD: 120p)",
    country_placeholder: "Quốc gia (VD: Việt Nam, Mỹ...)",
    genres_placeholder: "Thể loại (Hành động, Viễn tưởng...)",
    release_year_placeholder: "Năm phát hành",
    request_admin: "Yêu cầu quyền Quản trị",
    pending_approval: "Đang chờ duyệt...",
    welcome_admin: "Chào mừng Quản trị viên",
    choose_env: "Vui lòng chọn môi trường làm việc của bạn",
    admin_dashboard_btn: "Dashboard Quản trị",
    user_page_btn: "Trang Người dùng",
    manage_movies_desc: "Quản lý phim, người dùng & bình luận",
    user_exp_desc: "Trải nghiệm xem phim như người dùng",
    search_comm_placeholder: "Tìm kiếm người dùng, phim, nội dung...",
    all_comments: "Tất cả bình luận",
    reported_only: "Chỉ bị báo cáo",
    newest_first: "Mới nhất",
    oldest_first: "Cũ nhất",
    most_reported: "Bị báo cáo nhiều nhất",
    user_info: "Thông tin người dùng",
    movie_context: "Bộ phim",
    comm_content: "Nội dung bình luận",
    engagement: "Tương tác",
    actions: "Hành động",
    recent_reports: "Báo cáo gần đây:",
    reports_count: "BÁO CÁO",
    reply_to: "Phản hồi cho",
    sub_comment: "Bình luận phụ",
    edit_comm: "Sửa bình luận",
    delete_comm: "Xóa bình luận",
    back: "Quay lại",
    watch_history: "Lịch sử xem",
    activity_history: "Lịch sử hoạt động",
    recent_activity: "Hoạt động gần đây",
    admin_chat: "Admin Chat",
    groups: "Nhóm",
    create_group: "Tạo nhóm",
    create_new_group: "Tạo nhóm mới",
    group_name: "Tên nhóm",
    enter_group_name: "Nhập tên nhóm...",
    select_members: "Chọn thành viên",
    members: "thành viên",
    all_admins: "Tất cả Admin",
    private_messages: "Tin nhắn riêng",
    delete_conversation: "Xóa cuộc trò chuyện",
    confirm_delete_conversation: "Bạn có chắc chắn muốn xóa toàn bộ cuộc trò chuyện này để giải phóng bộ nhớ? Hành động này không thể hoàn tác.",
    confirm_delete_group: "Bạn có chắc chắn muốn xóa nhóm này?",
    group_name_and_members_required: "Vui lòng nhập tên nhóm và chọn ít nhất 1 thành viên",
    search_users: "Tìm kiếm người dùng...",

    admin_chat_room: "Admin Chat Room",
    admin_chat_desc: "Kênh trao đổi nội bộ giữa các Admin",
    admin_list: "Danh sách Admin",
    group_chat: "Group Chat",
    group_chat_desc: "Phòng chung",
    chat_with: "Chat với",
    private_chat_desc: "Cuộc trò chuyện riêng tư",
    chat_placeholder_group: "Nhập tin nhắn trao đổi với Admin khác...",
    chat_placeholder_private: "Nhắn tin cho {{name}}...",
    no_chat_group: "Chưa có tin nhắn nào. Hãy bắt đầu cuộc trò chuyện!",
    no_chat_private: "Bắt đầu cuộc trò chuyện riêng tư.",
    report: "Báo cáo",
    clear_all: "Xóa tất cả",
    confirm_delete_history: "Bạn có chắc chắn muốn xóa lịch sử này?",
    confirm_withdraw_comment: "Bạn có muốn thu hồi bình luận này?",
    confirm_delete_reply: "Bạn có muốn xóa phản hồi này?",
    history_deleted: "Đã xóa lịch sử thành công.",
    comment_withdrawn: "Bình luận đã được thu hồi.",
    reply_deleted: "Phản hồi đã được xóa thành công.",
    delete_error: "Lỗi! Không thể thực hiện yêu cầu xóa.",
    quick_user_manage: "Quản lý nhanh người dùng",
    ten_latest_members: "10 thành viên mới nhất",
    website_health: "Sức khỏe Website",
    traffic_7d: "Lượng truy cập 7 ngày qua",
    moderation_room: "Phòng kiểm duyệt",
    quick_movie_store: "Kho phim nhanh",
    genre_distribution: "Phân bổ theo thể loại",
    add_movie_now: "Thêm phim ngay",
    cleanup: "Dọn rác",
    view_details: "Xem chi tiết",
    need_more: "Cần đăng thêm!",
    approved: "Đã duyệt",
    rejected: "Đã từ chối",
    unban: "Mở khóa",
    ban: "Khóa",
    user_banned: "Thành công! Người dùng đã bị khóa.",
    user_unbanned: "Thành công! Người dùng đã được mở khóa.",
    role_updated: "Thành công! Quyền hạn đã được cập nhật.",
    upload_file_success: "Tải tệp lên thành công!",
    upload_file_error: "Thất bại! Không thể tải tệp lên.",
    updated_success: "Thành công! Dữ liệu đã được cập nhật.",
    cancel_edit: "Hủy sửa",
    active_7d: "Hoạt động (7 ngày)",
    peak_day: "Ngày cao điểm",
    avg_active: "Trung bình",
    growth: "Tăng trưởng",
    user_role: "Người dùng",
    admin_role: "Quản trị viên",
    banned_status: "Đã bị khóa",
    movie_id: "ID Phim",
    id_label: "ID",
    mon: "Thứ 2",
    tue: "Thứ 3",
    wed: "Thứ 4",
    thu: "Thứ 5",
    fri: "Thứ 6",
    sat: "Thứ 7",
    sun: "Chủ Nhật",
    edit_banner: "Sửa Banner",
    update_banner: "Cập nhật Banner",
    edit_movie: "Sửa Phim",
    update_movie: "Cập nhật Phim",
    banners: "Banners",
    image_url_placeholder: "URL Hình ảnh (hoặc tải lên bên dưới)",
    movie_data_error: "Lỗi dữ liệu phim.",
    movie_not_found: "Không tìm thấy phim.",
    reported_success: "Cảm ơn bạn! Báo cáo vi phạm đã được gửi thành công.",
    reply_posted: "Thành công! Phản hồi của bạn đã được đăng.",
    system_online: "Hệ thống đang trực tuyến.",
    logout_admin_success: "Đã đăng xuất an toàn khỏi Dashboard Quản trị.",
    live_status: "Trực tuyến",
    database_stats: "Dữ liệu",
    cinematic_exp: "Trải nghiệm điện ảnh đỉnh cao",
    newly_added: "Phim mới đăng",
    edited: "Đã chỉnh sửa",
    forgot_password_title: "Khôi phục mật khẩu",
    forgot_password_subtitle: "Nhập email của bạn để nhận mã xác thực OTP",
    send_otp: "Gửi mã OTP",
    enter_otp: "Nhập mã OTP",
    verify_otp: "Xác thực OTP",
    otp_sent: "Thành công! Mã OTP đã được gửi đến email của bạn.",
    otp_invalid: "Lỗi! Mã OTP không chính xác hoặc đã hết hạn.",
    reset_password_title: "Đặt lại mật khẩu mới",
    reset_password_btn: "Cập nhật mật khẩu",
    password_reset_success: "Chúc mừng! Mật khẩu đã được cập nhật thành công.",
    email_not_found: "Lỗi! Email không tồn tại trong hệ thống của chúng tôi.",
    resend_otp: "Gửi lại mã OTP",
    enter_new_password: "Nhập mật khẩu mới",
    support_user: "Hỗ trợ User",
    customer_support: "Hỗ trợ khách hàng",
    messages_from_users: "Tin nhắn từ người dùng",
    no_support_requests: "Chưa có yêu cầu hỗ trợ",
    support_label: "Hỗ trợ",
    type_response: "Nhập phản hồi cho người dùng...",
    select_conversation: "Chọn một cuộc trò chuyện",
    respond_to_user: "Phản hồi yêu cầu từ người dùng tại đây",
    admin_online: "Admin đang online",
    contact_support: "Liên hệ hỗ trợ",
    how_can_we_help: "Bạn cần hỗ trợ gì không?",
    send_us_a_message: "Gửi tin nhắn nếu bạn cần hỗ trợ nhé.",
    type_support_message: "Nhập tin nhắn hỗ trợ...",
    edited_label: "(đã chỉnh sửa)",
    support_moviezone: "Hỗ trợ MovieZone",
    online: "Trực tuyến",
    hello_user: "Chào bạn!",
    send_failed: "Thất bại! Gửi tin nhắn không thành công.",
    msg_withdrawn: "Tin nhắn đã được thu hồi thành công.",
    msg_updated: "Tin nhắn đã được cập nhật thành công.",
    confirm_withdraw_msg: "Bạn có chắc chắn muốn thu hồi tin nhắn này không?",
    genre_action: "Hành Động",
    genre_historical: "Cổ Trang",
    genre_war: "Chiến Tranh",
    genre_scifi: "Viễn Tưởng",
    genre_horror: "Kinh Dị",
    genre_comedy: "Hài Hước",
    genre_animation: "Hoạt Hình",
    genre_drama: "Tâm Lý",
    country_china: "Trung Quốc",
    country_korea: "Hàn Quốc",
    country_japan: "Nhật Bản",
    country_usa: "Mỹ",
    country_thailand: "Thái Lan",
    country_western: "Âu Mỹ",
  },
  en: {
    home: "Home",
    genres: "Genres",
    countries: "Countries",
    movies: "Movies",
    series: "TV Series",
    favorites: "Favorites",
    search_placeholder: "Search movies...",
    welcome: "Welcome",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    register: "Register",
    featured_movie: "Featured Movie",
    play_now: "Play Now",
    details: "Details",
    trending_week: "Trending Now",
    popular_keywords: "Popular Keywords",
    search_home_placeholder: "Search movies, actors...",
    search_btn: "Search",
    my_collection: "My Collection",
    empty_fav: "Empty List",
    explore_now: "Explore Now",
    update_profile: "Update Profile",
    username: "Username",
    email: "Email",
    password: "Password",
    new_password: "New Password",
    save_changes: "Save Changes",
    cancel: "Cancel",
    edit_profile: "Edit Profile",
    account_settings: "Account Settings",
    stats_fav: "Hearts",
    stats_comm: "Comments",
    stats_rate: "Ratings",
    community_rating: "Community Rating",
    your_thought: "Share your thoughts about this movie...",
    send_rating: "Send Rating",
    feeling: "Feeling:",
    footer_desc: "Discover millions of movies, TV shows and people. Explore now. Built with MERN Stack.",
    explore: "Explore",
    support: "Support",
    newsletter: "Newsletter",
    newsletter_desc: "Get the latest movie updates.",
    email_addr: "Email address",
    join: "Join",
    all_genres: "All Genres",
    release_year: "Release Year",
    login_title: "Welcome Back",
    login_subtitle: "Login to continue your cinematic experience.",
    no_account: "New to MovieZone?",
    have_account: "Already have an account?",
    register_title: "Create New Account",
    register_subtitle: "Join the MovieZone community today.",
    remember_me: "Remember me",
    forgot_password: "Forgot password?",
    social_login: "Or login with",
    error_required: "This field is required",
    error_email: "Invalid email address",
    error_password_min: "Password must be at least 6 characters",
    loading: "Loading...",
    no_results: "No results found",
    admin_dashboard: "Admin Dashboard",
    total_users: "Total Users",
    total_movies: "Total Movies",
    requests: "Requests",
    manage_movies: "Add Movie",
    recent_comments: "Recent Comments",
    back_to_top: "Back to top",
    success_update: "Success! Information has been updated.",
    error_update: "Failed! Unable to update information.",
    logged_out: "Logged out of the system.",
    invalid_credentials: "Invalid email or password",
    overview: "Overview",
    cast: "Cast",
    recommendations: "Recommendations",
    trailers: "Trailers & Teasers",
    rating: "Rating",
    status: "Status",
    runtime: "Runtime",
    country: "Country",
    minutes: "min",
    release_date: "Release Date",
    fav_removed: "Removed from favorites.",
    fav_added: "Added to favorites successfully!",
    fav_error: "An error occurred, please try again later.",
    empty_fav_desc: "You don't have any favorite movies yet. Explore and click the heart icon to save them!",
    movies_count: "Movies",
    fav_description: "Where your favorite movies are stored.",
    login_required_fav: "Please login to save favorites",
    login_required_comm: "Please login to post a comment",
    comment_posted: "Comment posted",
    comment_error: "Error posting comment",
    actors: "Actors",
    awards: "Awards",
    help_center: "Help Center",
    terms: "Terms of Use",
    privacy: "Privacy Policy",
    content_policy: "Content Policy",
    welcome_back: "Welcome back to MovieZone!",
    reg_success: "Registration successful! Welcome to MovieZone.",
    logout_success: "Logged out successfully. See you again!",
    upload_success: "Success! Avatar has been updated.",
    upload_error: "Error! Upload failed.",
    file_too_large: "File too large! Please choose under 2MB.",
    profile_updated: "Your profile has been updated successfully!",
    no_trailer: "No trailer available for this movie",
    copied_link: "Movie link copied!",
    save_fav: "Save",
    saved_fav: "Saved",
    liked: "Liked",
    share: "Share",
    views: "Views",
    no_comments: "No comments yet.",
    no_watch_history: "No watch history yet.",
    no_comments_yet: "You haven't left any comments yet.",
    no_liked_comments: "You haven't liked any comments yet.",
    no_replies_yet: "You haven't replied to any comments yet.",
    view_on_movie: "View on movie",
    view_source: "View source",
    view_movie: "View movie",
    replied_to: "Replied to",
    you_liked_this: "You liked this",
    withdraw: "Withdraw",
    you_wrote: "You wrote",
    like: "Like",
    reply: "Reply",
    admin_manage_users: "User Management",
    account: "Account",
    recently_updated: "Recently Updated",
    hot_series: "Hot Series",
    new_movies: "New Movies",
    top_rated: "Top Rated Movies",
    explore_all: "Explore all movies",
    explore_more: "Explore more",
    view_all_results: "View all search results",
    loading_experience: "Loading experience...",
    save: "Save",
    saving: "Saving...",
    admin_system: "Content Management System",
    preview_site: "Preview Site",
    pending_requests: "Pending Requests",
    manage_comments: "Manage Comments",
    add_banner: "Add Banner",
    add_movie: "Add Movie",
    save_banner: "Save Banner",
    save_movie: "Save Movie",
    select_movie: "Select Linked Movie (Optional)",
    external_link: "External Link (Optional)",
    title: "Title",
    description: "Description",
    poster_url: "Poster URL",
    trailer_url: "Trailer URL (Youtube)",
    runtime_placeholder: "Runtime (e.g. 120 min)",
    country_placeholder: "Country (e.g. USA, Vietnam...)",
    genres_placeholder: "Genres (Action, Sci-Fi...)",
    release_year_placeholder: "Release Year",
    request_admin: "Request Admin Role",
    pending_approval: "Pending Approval...",
    welcome_admin: "Welcome Admin",
    choose_env: "Please choose your working environment",
    admin_dashboard_btn: "Admin Dashboard",
    user_page_btn: "User Interface",
    manage_movies_desc: "Manage movies, users & comments",
    user_exp_desc: "Experience the app as a regular user",
    search_comm_placeholder: "Search user, movie, content...",
    all_comments: "All Comments",
    reported_only: "Reported Only",
    newest_first: "Newest First",
    oldest_first: "Oldest First",
    most_reported: "Most Reported",
    user_info: "User Info",
    movie_context: "Movie Context",
    comm_content: "Comment Content",
    engagement: "Engagement",
    actions: "Actions",
    recent_reports: "Recent Reports:",
    reports_count: "REPORTS",
    reply_to: "Reply to",
    sub_comment: "Sub-Comment",
    edit_comm: "Edit Comment",
    delete_comm: "Delete Comment",
    back: "Back",
    watch_history: "Watch History",
    activity_history: "Activity History",
    recent_activity: "Recent Activity",
    admin_chat: "Admin Chat",
    groups: "Groups",
    create_group: "Create Group",
    create_new_group: "Create New Group",
    group_name: "Group Name",
    enter_group_name: "Enter group name...",
    select_members: "Select Members",
    members: "members",
    all_admins: "All Admins",
    private_messages: "Private Messages",
    delete_conversation: "Delete Conversation",
    confirm_delete_conversation: "Are you sure you want to delete this entire conversation to free up storage? This action cannot be undone.",
    confirm_delete_group: "Are you sure you want to delete this group?",
    group_name_and_members_required: "Please enter a group name and select at least 1 member",
    search_users: "Search users...",

    admin_chat_room: "Admin Chat Room",
    admin_chat_desc: "Internal channel for Admin communication",
    admin_list: "Admin List",
    group_chat: "Group Chat",
    group_chat_desc: "Public Room",
    chat_with: "Chat with",
    private_chat_desc: "Private conversation",
    chat_placeholder_group: "Type a message to other Admins...",
    chat_placeholder_private: "Message {{name}}...",
    no_chat_group: "No messages yet. Start a conversation!",
    no_chat_private: "Start a private conversation.",
    report: "Report",
    clear_all: "Clear All",
    confirm_delete_history: "Are you sure you want to delete this history?",
    confirm_withdraw_comment: "Are you want to withdraw this comment?",
    confirm_delete_reply: "Are you want to delete this reply?",
    history_deleted: "History deleted successfully.",
    comment_withdrawn: "Comment has been withdrawn.",
    reply_deleted: "Reply has been deleted successfully.",
    delete_error: "Error! Failed to delete.",
    genre_action: "Action",
    genre_historical: "Historical",
    genre_war: "War",
    genre_scifi: "Sci-Fi",
    genre_horror: "Horror",
    genre_comedy: "Comedy",
    genre_animation: "Animation",
    genre_drama: "Drama",
    country_china: "China",
    country_korea: "Korea",
    country_japan: "Japan",
    country_usa: "USA",
    country_thailand: "Thailand",
    country_western: "Western",
    quick_user_manage: "Quick User Management",
    ten_latest_members: "10 Latest Members",
    website_health: "Website Health",
    traffic_7d: "Traffic over the last 7 days",
    moderation_room: "Moderation Room",
    quick_movie_store: "Quick Movie Store",
    genre_distribution: "Genre Distribution",
    add_movie_now: "Add Movie Now",
    cleanup: "Cleanup",
    view_details: "View Details",
    need_more: "Need more!",
    approved: "Approved",
    rejected: "Rejected",
    unban: "Unban",
    ban: "Ban",
    user_banned: "Success! User has been banned.",
    user_unbanned: "Success! User has been unbanned.",
    role_updated: "Success! Role has been updated.",
    upload_file_success: "File uploaded successfully!",
    upload_file_error: "Failed! Unable to upload file.",
    updated_success: "Success! Data has been updated.",
    cancel_edit: "Cancel Edit",
    active_7d: "Active (7d)",
    peak_day: "Peak Day",
    avg_active: "Avg Active",
    growth: "Growth",
    user_role: "User",
    admin_role: "Admin",
    banned_status: "Banned",
    movie_id: "Movie ID",
    id_label: "ID",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    edit_banner: "Edit Banner",
    update_banner: "Update Banner",
    edit_movie: "Edit Movie",
    update_movie: "Update Movie",
    banners: "Banners",
    image_url_placeholder: "Image URL (or upload below)",
    movie_data_error: "Error loading movie data.",
    movie_not_found: "Movie not found.",
    reported_success: "Thank you! Report submitted successfully.",
    reply_posted: "Success! Your reply has been posted.",
    system_online: "System is online.",
    logout_admin_success: "Safely logged out from Admin Dashboard.",
    live_status: "Live",
    database_stats: "Database",
    cinematic_exp: "Ultimate Cinematic Experience",
    newly_added: "Newly Added",
    edited: "Edited",
    forgot_password_title: "Reset Password",
    forgot_password_subtitle: "Enter your email to receive an OTP code",
    send_otp: "Send OTP",
    enter_otp: "Enter OTP",
    verify_otp: "Verify OTP",
    otp_sent: "Success! OTP code has been sent to your email.",
    otp_invalid: "Error! Invalid or expired OTP code.",
    reset_password_title: "Set New Password",
    reset_password_btn: "Update Password",
    password_reset_success: "Congratulations! Password reset successful.",
    email_not_found: "Error! Email not found in our system.",
    resend_otp: "Resend OTP",
    enter_new_password: "Enter new password",
    support_user: "User Support",
    customer_support: "Customer Support",
    messages_from_users: "Messages from users",
    no_support_requests: "No support requests yet",
    support_label: "Support",
    type_response: "Type a response to the user...",
    select_conversation: "Select a conversation",
    respond_to_user: "Respond to user requests here",
    admin_online: "Admin is online",
    contact_support: "Contact Support",
    how_can_we_help: "How can we help you?",
    send_us_a_message: "Send us a message if you need help.",
    type_support_message: "Type a support message...",
    edited_label: "(edited)",
    support_moviezone: "MovieZone Support",
    online: "Online",
    hello_user: "Hello!",
    send_failed: "Failed! Message delivery unsuccessful.",
    msg_withdrawn: "Message withdrawn successfully.",
    msg_updated: "Message updated successfully.",
    confirm_withdraw_msg: "Are you sure you want to withdraw this message?",
  }
};
